version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - database
    environment:
      APP_KEY: base64:WIdOqUmWTND7GcuD19geLATo0dl8sla2X9E8DzkBWto=

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    environment:
      REACT_APP_API_URL: http://localhost:8000/api

  database:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_ROOT_PASSWORD: secret